### ISSUE TITLE
[SNES] Kunio-kun no Dodge Ball Da yo Zenin Shuugou! - Tournament Special - doesn't boot [ares-v127]

### ISSUE THREAD

**Issue by Max833** [higan-emu/ares#431]
Kunio-kun no Dodge Ball Da yo Zenin Shuugou! - Tournament Special doesn't boot.

Probably because of a board entry issue: https://archive.ph/GlXj8

**Comment by LukeUsher** [comment]
Fixed as of [93e8944](https://github.com/ares-emulator/ares/commit/93e89446e2d83f2084a20924f3cf4ac26fe78a03)

**Comment by Max833** [comment]
@LukeUsher 
**Yuuyu no Quiz de Go! Go! (Japan)** ist working now, but **From TV Animation Slam Dunk - Shuueisha Limited (Japan)** and **Kunio-kun no Dodge Ball Da yo Zenin Shuugou! - Tournament Special**... they still don't work, unfortunately. Maybe this is helpful:


https://github.com/bsnes-emu/bsnes/commit/3d646aef73a1e1468b4b0bb5c3ffed0fc28eb180 (added SHVC-2P3B-01)

https://github.com/bsnes-emu/bsnes/commit/409dd371b96e863ea626f85faa51db140307d275) (added SHVC-4PV5B-01)

**Comment by LukeUsher** [comment]
hmm, I did add the boards, but I forgot to recompile the resources, so mia didn't use the new database, my bad

Unless I messed up elsewhere, this should be fixed latest commit.

**Comment by Max833** [comment]
As soon as the new version is available, I will try it. Thank you!

**Comment by Max833** [comment]
It is working perfectly now! =)
