### ISSUE TITLE
Ares v129 crashes when rapidly dragging and dropping N64 ROMs onto the Ares window

### ISSUE THREAD

**Issue by DerekTurtleRoe** [higan-emu/ares#688]
Ares v129 crashes when rapidly dragging and dropping N64 ROMs onto the Ares window from the Windows file explorer. I noticed this behavior with Ares v128 as well.

**To Reproduce**
1. Open Ares on Windows (Vulkan enabled)
2. Drag and drop a ROM onto Ares
3. Drag and drop another ROM onto Ares
4. Repeat until it crashes

**Expected behavior**
Dragging and dropping ROMs rapidly shouldn't crash Ares.

**Additional context**
Specifically I was dragging and dropping test ROMs onto Ares, such as those from krom's test suite, Rasky, Dillon, etc.

The faster you do so the more likely the crash. Hiro bug perhaps?

My system:

Ares v129
Windows 10 Pro version 21H1 OS build 19043.1889
Intel i5-6600K
32GB of DDR4 3200MHz RAM
Nvidia EVGA GTX 1080 SuperClocked

Not sure if relevant, but I was using the Direct3D 9.0 video driver and the XAudio 2.1 audio driver.

**Comment by DerekTurtleRoe** [comment]
Side note: sometimes it crashes when unloading ROMs as well as loading them.

**Comment by DerekTurtleRoe** [comment]
Update: It seems to be around 5 ROMs for some reason...I can consistently get it to crash at under 5 ROMs. Sometimes 4, but 5 usually it is guaranteed to crash. 🤔

**Comment by DerekTurtleRoe** [comment]
Using the MAME RDP instead of the Parallel-RDP with Vulkan seems to fix the issue, so might not be Hiro after all? I don't know much about the code base, tbh.

**Comment by FitzRoyX** [comment]
Is it a specific system's roms, like n64? Can you get it to happen with another system?

**Comment by DerekTurtleRoe** [comment]
@FitzRoyX Specifically I was testing N64 ROMs, yeah.

But I can't get it to crash with NES or SNES ROMs, so must be something with the N64 core specifically, and maybe with the Vulkan part of it?

Update: tried with a few other systems and was only able to get it to crash with the N64 core and with Vulkan enabled.

**Comment by LukeUsher** [comment]
Have you tried the latest nightly builds? a related issue was fixed in https://github.com/ares-emulator/ares/commit/e0434ca82b79648453383090ea4b550d6353c36e

**Comment by kev4cards** [comment]
I tried this in fcef806 and can reproduce the problem. However, it seems specific to krom's test ROM's. That said, I have not incorporated in any other test ROM's into the mix.

Dragging and dropping one retail game after another onto ares did not cause a crash. So, maybe parallel-rdp (or the Ares side of parallel-rdp) does not handle memory well when changing from one screen of static information to the next?

System: Windows 10 Home 21H2 (Build 19044.1865) OS, Intel i7-9750H CPU, Nvidia GTX 1660 Ti GPU, 16 GB 2666 MHz DDR4 RAM

**Comment by rasky** [comment]
Can you write down a sequence of specific ROMs that can reliably reproduce the crash? Bonus points if they are all open sources (eg: all krom’s)

**Comment by kev4cards** [comment]
As discussed on the Ares Discord server, attached is the MSYS2 gdb backtrace after dragging and dropping the krom tests CPUADD.N64 and CPUADDU.N64, respectively. The ParaLLEl-RDP upscaling is set to "UHD Quality."
[ares-ebde92c N64 test ROM crash backtrace.txt](https://github.com/ares-emulator/ares/files/9419754/ares-ebde92c.N64.test.ROM.crash.backtrace.txt)

**Comment by DerekTurtleRoe** [comment]
Using any of the krom tests I can reliably get the emulator to crash with any quality setting, and either 4 or 5 ROMs is always the limit for me. Same with Dillons test ROMs. This does happen with official games, although it's very rare for that to happen.

@LukeUsher This still happens on the latest nightly build as well, including the Clang build. Tried all the same variations of settings and the only thing that fixed the issue was using the MAME RDP instead of Parallel-RDP.

@rasky Sure. Using Dillons test ROMs do ADDIU.z64, ADDU.z64, AND.z64, ANDI.z64, and then BASIC.z64. It should crash if you are using Vulkan/Parallel-RDP and not the MAME RDP.

Links to the test ROMs:

https://github.com/Dillonb/n64-tests
https://github.com/PeterLemon/N64

**Comment by Themaister** [comment]
I think the problem here is that the scanout Vulkan::BufferHandle is not freed properly before the device is destroyed. Is there a way to block the video deinit on making sure the async scanout is actually performed?

**Comment by DerekTurtleRoe** [comment]
@Themaister Funny you should mention that actually, but I have had a similar issue with other emulators using Parallel-RDP. Project64 every once in a while will crash when loading a ROM I know works fine, and sometimes m64p crashes in the same way.

UPDATE: I just tested BizHawk and the same things happen. If you switch from the MAME RDP to Parallel-RDP it starts exhibiting all the same crashes. This is with the Ares performance core, as that is the one with Parallel-RDP. simple64, Mupen64Plus, and Mupen64Plus-Next all also have this behavior.

I can't be certain they are all the same issue, but I also can say that they are very similar and occur nearly all at the same time (during loading and unloading). So if we can figure out what is causing this we might be able to fix a bug in several emulators at once.

**Comment by Jj0YzL5nvJ** [comment]
Themaister/parallel-rdp-standalone#3

**Comment by Themaister** [comment]
Merged the fix.
